### ISSUE TITLE
Не удобно работать с джобами

### ISSUE THREAD

**Issue by Dmitry908** [PixeyeHQ/actors.unity#45]
Не удобно работать с джобами для перемещения обьектов в параллельности. 
Суть: не используется очистка групп от сущностей через фреймворк акторсов, вместо этого через дополнительные проверки пропускаются сущности, которые должны уйти из группы.

вся логика "мучений" подписана в ProcessingJobsMoveDirection ))
после запуска нажимать пробел
[issuesActrosJob.zip](https://github.com/PixeyeHQ/actors.unity/files/4807814/issuesActrosJob.zip)

**Comment by Dmitry908** [comment]
примечание.
в данном примере не обязательно на каждом кадре обновлять StructMoveDirection, но 
 под продакшен пойдет движение, скорость которого меняется на каждом кадре.

**Comment by PixeyeHQ** [comment]
Done.
