### ISSUE TITLE
🐞 ACTORS_EVENTS_MANUAL doesn't work correctly 

### ISSUE THREAD

**Issue by GariestGary** [PixeyeHQ/actors.unity#62]
![Screenshot_1](https://user-images.githubusercontent.com/38670681/86573913-78baf100-bf8e-11ea-9d3b-21aca6c4800e.png)

**Comment by PixeyeHQ** [comment]
@GariestGary какая версия?

**Comment by GariestGary** [comment]
2019.4.1f1

**Comment by PixeyeHQ** [comment]
не юнити - какая версия фреймворка

**Comment by GariestGary** [comment]
последний релиз 2020.06.4

**Comment by PixeyeHQ** [comment]
Я правильно понимаю что ты не установил фреймворк через манифест, а скачал его себе в проект с релизов?

**Comment by GariestGary** [comment]
скачал .unitypackage и добавил в проект, как сказано в разделе How to Install в в пункте Manual installation

**Comment by MyMyGames** [comment]
надо проверить ASMDEF файлы проекта, чтобы там были в блоках указаны валидные ссылки на Actors
https://prnt.sc/tcmma3

**Comment by PixeyeHQ** [comment]
https://i.gyazo.com/241e17327a55ad7ba1d73ade8bd54a70.mp4 только что проверял на пустом проекте - все норм, у тебя есть ASMDEF файлы, может быть какие то кастомные плагины/редакторы?

**Comment by PixeyeHQ** [comment]
@GariestGary Все, я понял в чем ошибка, у тебя в Build Settings стоит ACTORS_EVENTS_MANUAL - из-за него. Сейчас поправлю

**Comment by PixeyeHQ** [comment]
@GariestGary подмени файлы внутри актора на скаченные с мастер ветки. Будет работать.  Для простоты также сделай так:
https://i.gyazo.com/9be671b61d92ddc00139b8e7f0f976b4.mp4 чтобы перейти на авто события в екс группах. Ручные вряд ли тебе понадобятся
